---
include:
    - board: xiao_ble//zmk
      shield: totem_left
      artifact-name: totem_left_dongle
      cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    - board: xiao_ble//zmk
      shield: totem_right
      artifact-name: totem_right_dongle
      cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    - board: xiao_ble//zmk
      shield: totem_dongle prospector_adapter_battery
      artifact-name: totem_dongle
    - board: xiao_ble//zmk
      shield: totem_left
      artifact-name: totem_left_direct
      cmake-args: >-
        -DCONFIG_ZMK_SPLIT=y
        -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
        -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1
        -DCONFIG_BT_MAX_CONN=6
        -DCONFIG_BT_MAX_PAIRED=6
        -DCONFIG_ZMK_SLEEP=n
        -DCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
        -DCONFIG_BT_CTLR_TX_PWR_PLUS_8=y
        -DCONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
        -DCONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
        -DCONFIG_BT_PERIPHERAL_PREF_LATENCY=0
    - board: xiao_ble//zmk
      shield: totem_right
      artifact-name: totem_right_direct
      cmake-args: >-
        -DCONFIG_ZMK_SPLIT=y
        -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
        -DCONFIG_ZMK_SLEEP=n
        -DCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
        -DCONFIG_BT_CTLR_TX_PWR_PLUS_8=y
        -DCONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
        -DCONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
        -DCONFIG_BT_PERIPHERAL_PREF_LATENCY=0
    - board: xiao_ble//zmk
      shield: settings_reset
      artifact-name: settings_reset
