name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "build.yaml"
      - "config/*.conf"
      - "config/*.keymap"
      - "config/boards/shields/totem/*"
      - "config/includes/*.dtsi"
      - "config/keypos_def/*.h"
      - "config/west.yml"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "build.yaml"
      - "config/*.conf"
      - "config/*.keymap"
      - "config/boards/shields/totem/*"
      - "config/includes/*.dtsi"
      - "config/keypos_def/*.h"
      - "config/west.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
