name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "build.yaml"
      - "config/*.conf"
      - "config/*.keymap"
      - "config/CMakeLists.txt"
      - "config/Kconfig"
      - "config/boards/shields/**"
      - "config/dts/**"
      - "config/include/**"
      - "config/includes/*.dtsi"
      - "config/keypos_def/*.h"
      - "config/src/**"
      - "config/west.yml"
      - "config/zephyr/**"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "build.yaml"
      - "config/*.conf"
      - "config/*.keymap"
      - "config/CMakeLists.txt"
      - "config/Kconfig"
      - "config/boards/shields/**"
      - "config/dts/**"
      - "config/include/**"
      - "config/includes/*.dtsi"
      - "config/keypos_def/*.h"
      - "config/src/**"
      - "config/west.yml"
      - "config/zephyr/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
